### ISSUE TITLE
export default request, like as other fetch library.

### ISSUE THREAD

**Issue by timakin** [axross/ffetch#1]
https://github.com/axross/easyagent/blob/master/src/EasyAgent.es6#L118

An exportation of module with self-righteous name disturbs users from consistent use.

**Comment by axross** [comment]
Thank you for make the suggestion.

There is no way that interfaces of `request` is unified. There is a possibility that it causes confusion.

If you insist, you can use like this:

``` javascript
import request from 'easyagent';
```

**Comment by timakin** [comment]
gotcha :D
