### ISSUE TITLE
can't accept sending with cookie, like fetch/es6

### ISSUE THREAD

**Issue by snghrsw** [axross/ffetch#3]
I want insert credentials option from fetch/es6.
 **credentials: 'include'**
## fetch

```
fetch('/post?type=fetch', {
    credentials: 'include', 
}
```

Can EasyAgent do it like this?

```
EasyAgent
  .post(...)
  .setHeaders({
    credentials: 'include'
  })
```

or

```
EasyAgent({credentials: 'include'})
  .post(URL)
  .setJson(...)
```

Reference: https://developers.google.com/web/updates/2015/03/introduction-to-fetch

**Comment by axross** [comment]
@snghrym 

Thank you for posting your issue :)

I updated EasyAgent to `v0.0.5`.

It can receive some new options. I think your issue is solved now. Look this:

``` javascript
EasyAgent.post('/some/api/', {
  crendetials: 'include',
})
   .setJson(/* ... */)
  .fetch()
...
```

Have fun to use! :)

**Comment by snghrsw** [comment]
thank you for your high speed response.
